/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:32619dc1-4b75-4f75-a20b-1f27d4bee3c2",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_5ecCWoMru",
    "aws_user_pools_web_client_id": "7nbu8u7cdjk3egb59stt6el49u",
    "oauth": {}
};


export default awsmobile;
